spring.application.name=logyourmeals


spring.datasource.url=jdbc:postgresql://localhost:5432/logyourmeals
spring.datasource.username=postgres
spring.datasource.password=postgres



server.port=8080

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=create


twilio.account.sid=AC686ef5b55d0f398d20bd126cf6c6e163
twilio.auth.token=87c3acd21c777313c94639715215899b
twilio.whatsapp.number=whatsapp:+14155238886f

